# Spring Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/fintax_db
spring.datasource.username=postgres
spring.datasource.password=pgselva12345$
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8080

# Logging Configurations
logging.level.org.springframework.security=INFO
logging.level.com.fintax.pro=DEBUG

# JWT Configuration Defaults
fintax.jwt.secret=9a67471ec63910c850d995968532470c14b886291a2b8e390c5f212217c24467
fintax.jwt.expiration-ms=86400000

# Google Gemini AI Configuration
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent



